const { withXcodeProject } = require('@expo/config-plugins');

// Selfinder has no Mac-native experience — the PC/desktop experience is the
// website (selfinder.online), not this app. iOS apps are, by default,
// runnable unmodified on Apple Silicon Macs ("Designed for iPad" in
// Xcode's target destinations), which is what Apple's ITMS-90863 warning
// on every build is actually about: expo-modules-core's native symbols
// aren't all present in the macOS-compatible slice, since Expo doesn't
// build/test against that target. Since ios/ is regenerated by `expo
// prebuild` on every build (gitignored, not hand-edited), the fix has to
// live here as a config plugin rather than as a one-off Xcode setting
// change, or it would be silently wiped on the next build.
//
// SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD = NO is the exact Xcode build
// setting behind unchecking "Mac (Designed for iPad)" from a target's
// Supported Destinations list in the General tab.
module.exports = function withNoMacSupport(config) {
  return withXcodeProject(config, (config) => {
    config.modResults.addBuildProperty('SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD', 'NO');
    return config;
  });
};
