const Labels = [
  "✨ the subconscious ✨",
  "🌌 universal truth 🌌",
  "🧠 Inner Wisdom",
  "🌙 dream memory",
  "🌊 emotional current",
  "🪞 mirrored truth",
  "💭 thought fragment",
  "🌌 universal truth",
  "🔍 inner inquiry",
  "🌠 celestial whisper",
  "✦ star-seeded knowing",
  "☄ cosmic alignment",
  "🔮 divine remembrance",
  "⟡ message from the void",
  "🌀 personal rebirth",
  "🌱 seed of awakening",
  "✧ a new frequency",
  "🌿 the becoming",
  "🦋 metamorphic insight",
  "🌐 holographic insight",
  "🗝 key from nowhere",
  "🧩 unexpected clarity",
  "✨ intuitive flicker",
  "🎡 the child’s view",
  "🐚 whisper from within",
  "🎲 divine play",
  "🕊 inner permission",
  "🌸 sacred permission",
  "🫀 truth in stillness",
  "✨ soul nudge",
  "🔥 heart ignition",
  "💜 soft knowing",
  "💎 unfolding potential",
];

export default Labels;
