name: renovate

on:
  schedule:
    - cron: "0 3 * * 1"

  #    for the manual
  workflow_dispatch:
    inputs:
      runNow:
        description: "run renovate now"
        required: true
        default: "true"

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run
        uses: renovatebot/github-action@v40.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
